name: tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

env:
  FORCE_COLOR: 1
  PY_COLORS: 1

jobs:
  tests:
    runs-on: ubuntu-latest
    name: run tests
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: pyproject.toml
      - run: pip install -e .
      - run: pip install pytest
      - run: python3 -m pytest test_stubdefaulter.py
