name: Pycroscope

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

env:
  PYO3_USE_ABI3_FORWARD_COMPATIBILITY: 1

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: "3.10"
            uv-python-version: "3.10"
          - python-version: "3.11"
            uv-python-version: "3.11"
          - python-version: "3.12"
            uv-python-version: "3.12"
          - python-version: "3.13"
            uv-python-version: "3.13"
          - python-version: "3.14"
            uv-python-version: "3.14"
          - python-version: "3.15-dev"
            uv-python-version: "3.15"
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.uv-python-version }}
      - run: PYTHONPATH=. uv run --frozen -m pycroscope --config-file pyproject.toml stubdefaulter/
